import { Suspense } from 'react';
import NavSearch from '../components/NavSearch';
import Loading from '../components/LoaderSpiner';


export const metadata = {
  title: 'Search',
  description: 'Generated by Gloria',
}

export default function SearchLayout({ children }) {
  return (
    <>

      <NavSearch />
      <Suspense fallback={<Loading />}>
        {children}
      </Suspense>

    </>
  )
}
