import { Suspense } from 'react';
import './globals.css';
import { Raleway } from 'next/font/google';
import Image from 'next/image';
import Link from 'next/link';
import Nav from './components/Nav';
import Loading from './loading';
const raleway = Raleway({
  weight: '400',
  subsets: ['latin'],
  display: 'swap'
})

export const metadata = {
  title: 'Prueba Frontend Hackathon Jump2Digital',
  description: 'Generated by Gloria',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <container className="min-h-screen">
          <Link href="/personatges/1"><div className="flex w-full justify-center my-5">
            <Image src="/rick_and_morty.png" alt="Logo Rick and Morty"
              width={213.33} height={65} quality={80} priority={true}
              className="w-8/12 sm:w-5/12 max-w-sm" /></div>
          </Link>
          {/*  <Nav /> */}
          <Suspense fallback={<Loading />}>
            {children}
          </Suspense>
        </container >
      </body>
    </html>
  )
}
