import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Prueba Frontend Hackathon Jump2Digital',
  description: 'Generated by Gloria',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <container>
          <div className="flex w-full justify-center my-5"><img src="/rick_and_morty.png" alt="Logo Rick and Morty" className="w-8/12 sm:w-5/12 max-w-sm" /></div>

          {children}
        </container >
      </body>
    </html>
  )
}
