import { Suspense } from 'react';
import { Raleway } from 'next/font/google';
import Nav from '../../../app/components/Nav';
import Loading from '../../../app/loading';

const raleway = Raleway({
  weight: '400',
  subsets: ['latin'],
  display: 'swap'
})

export const metadata = {
  title: 'Personatges - Paginació',
  description: 'Generated by Gloria',
}

export default function PaginasPersonatgesLayout({ children }) {
  return (
    <>

      <Nav />
      <Suspense fallback={<Loading />}>
        {children}
      </Suspense>

    </>
  )
}
